POST http://localhost:3000/api/create-stripe-customer?API_ROUTE_SECRET= HTTP/1.1
Content-Type: application/json

{
  "record": {
    "email": "john@test.com",
    "id": "ea200ddc-6a2b-4139-abe2-35af0f754fda"
  }
}